### ISSUE TITLE
BooleanCondition

### ISSUE THREAD

**Issue by michaelferracane** [robin900/gspread-formatting#25]
Conditional Formatting on Python 3 unable to take more than length of 1

Sample code:

    new_rule = ConditionalFormatRule(
            ranges=[GridRange.from_a1_range('B1:B10000', wks)],
            booleanRule=BooleanRule(
                condition=BooleanCondition('TEXT_EQ', 'Tier 0' ),
                format=CellFormat(textFormat=TextFormat(bold=True))
            )
        )

Error:

ValueError: BooleanCondition.values has inappropriate length/content for condition type TEXT_EQ

**Comment by robin900** [comment]
@michaelferracane The second argument to `BooleanCondition()` is a tuple or list of values -- when using `TEXT_EQ`, the list should have one value. Thus:
```
BooleanCondition('TEXT_EQ', ['Tier 0'])
```

**Comment by robin900** [comment]
Note: The use of a `values` list instead of a `*varargs` matches the Sheets API, and allows for seamless roundtrip serialization/deserialization with API requests and responses. Enough people have been surprised by this fact, however, that I think I should at least provide a better exception message to remind the user that a list/tuple object is expected in all cases.

**Comment by robin900** [comment]
Release 0.3.4 is now in PyPI and has the improved exception message.
